# Generated by Django 5.2.5 on 2026-02-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_message_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.CharField(auto_created=True, max_length=100, null=True),
        ),
    ]
