# Generated by Django 5.2.5 on 2026-02-01 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_message_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.TextField(max_length=1000)),
                ('answer', models.CharField(max_length=100)),
                ('riddle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.message')),
            ],
        ),
    ]
