# Generated by Django 5.2.5 on 2026-02-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
