# Generated by Django 5.2.5 on 2026-02-02 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='riddle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riddles', to='Main.message'),
        ),
    ]
