# Generated by Django 5.2.5 on 2026-02-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_riddle_riddle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField(max_length=1000)),
                ('hint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='Main.riddle')),
            ],
        ),
    ]
