# Generated by Django 5.2.5 on 2026-02-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='riddle',
            name='hint',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Hint',
        ),
    ]
